-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM (
  'PENDING_PAYMENT',
  'PENDING_PAY_ACK',
  'PAID',
  'DELIVERED',
  'REJECTED',
  'EXPIRED',
  'REFUND_REQUESTED',
  'REFUND_APPROVED',
  'REFUND_REJECTED'
);
